/*
	 VIEWS ARE SAVED QUERIES THAT YOU CAN CREATE IN YOUR DATABASE. A SINGLE
	VIEW CAN REFERENCE ONE OR MORE TABLES.
	 
	 YOU CAN USE VIEWS AS A SOURCE FOR YOUR QUERIES IN MUCH THE SAME WAY AS
	TABLES. HOWEVER, VIEWS DON'T PERSISTENTLY STORE DATA; THE DEFINITION OF
	YOUR VIEW IS UNPACKED AT RUNTIME AND THE SOURCE OBJECTS ARE QUERIED.

	 YOUR APPLICATION CAN BE WRITTEN TO USE VIEWS INSTEAD OF THE UNDELYING
	TABLES, SHIELDING THE APPLICATION FROM MAKING CHANGES TO THE TABLES. THIS
	PROVIDES YOU WITH AN ADDITIONAL LAYER OF SECURITY FOR YOUR DATA.

	 AS LONG AS THE VIEW CONTINUES TO PRESENT THE SAME STRUCTURE TO THE CALLING
	APPLICATION, THE APPLICATION WILL ALSO RECEIVE CONSISTENT RESULTS. THIS WAY,
	VIEWS CAN BE CONSIDERED AN APPLICATION PROGRAMMING INTERFACE (API) TO A DATA-
	BASE FOR PURPOSES OF RETRIEVING DATA.
*/

CREATE VIEW SalesLT.CustOrders
AS
SELECT
	o.CustomerID,
	DATEADD(month, DATEDIFF(month, 0, o.OrderDate), 0) AS OrderMonth,
	SUM(od.OrderQty) AS Quantity
FROM
	SalesLT.SalesOrderHeader AS o
INNER JOIN
	SalesLT.SalesOrderDetail AS od
	ON od.SalesOrderID = o.SalesOrderID
GROUP BY
	o.CustomerID, DATEADD(month, DATEDIFF(month, 0, o.OrderDate), 0);
/*
SELECT
	OrderMonth,
	Quantity
FROM
	SalesLT.CustOrders;
*/
