SELECT color FROM SalesLT.Product
WHERE ProductID BETWEEN 500 AND 750
INTERSECT
SELECT color FROM SalesLT.Product
WHERE ProductID BETWEEN 751 AND 1000;

SELECT color FROM SalesLT.Product
WHERE ProductID BETWEEN 500 and 750
EXCEPT
SELECT color FROM SalesLT.Product
WHERE ProductID BETWEEN 751 and 1000;

SELECT color FROM SalesLT.Product
WHERE ProductID BETWEEN 751 and 1000
EXCEPT
SELECT color FROM SalesLT.Product
WHERE ProductID BETWEEN 500 and 750; 